version: '3.8'

services:
  cockroachdb:
    image: cockroachdb/cockroach:latest
    container_name: cockroach
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8081:8080"
    environment:
      - COCKROACH_USER=root
    networks:
      - closed-network
    volumes:
      - cockroach-data:/cockroach/cockroach-data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my-stocks-backend
    env_file:
      - local.env
    ports:
      - "8080:8080"
    depends_on:
      - cockroachdb
    networks:
      - closed-network
      - open-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my-stocks-frontend
    environment:
      - VITE_STOCKS_API_URL=http://localhost:8080
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - open-network

volumes:
  cockroach-data:

networks:
  closed-network:
    driver: bridge
  open-network:
    driver: bridge
