version: '3.8'

services:
  cockroachdb:
    image: cockroachdb/cockroach:latest
    container_name: cockroach
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8081:8080"
    environment:
      - COCKROACH_USER=root
    networks:
      - app-network
    volumes:
      - cockroach-data:/cockroach/cockroach-data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my-stocks-backend
    environment:
      - DATABASE_URL=postgresql://root@cockroachdb:26257/stocks_db?sslmode=disable
      - FETCH_DELAY_S=60
      - INFO_API_URL=https://stocks.algobook.info/api/v1/stocks
      - INFO_API_TOKEN=mock-token
      - RATINGS_API_URL=https://8j5baasof2.execute-api.us-west-2.amazonaws.com/production/swechallenge/list
      - RATINGS_API_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdHRlbXB0cyI6MSwiZW1haWwiOiJhbHZhcm8uYmFjY2EucGVuYUBnbWFpbC5jb20iLCJleHAiOjE3NDI1MDI0NzYsImlkIjoiMCIsInBhc3N3b3JkIjoiJyBPUiAnMSc9JzEifQ.G6lKAH0mJdLHkvl1TCez8uqte5t_yHTVBY_HW7_FjN0
    ports:
      - "8080:8080"
    depends_on:
      - cockroachdb
    networks:
      - app-network

volumes:
  cockroach-data:

networks:
  app-network:
    driver: bridge
